### ISSUE TITLE
DAO Status Links Wireframes

### ISSUE THREAD

**Issue by BOC111** [tiki/app#568]
The status page is where a registered/validated user will go to take any action. Think of it as the jump-off point for the user.

The DAO Status contains five elements (Draft wireframe below the list).

1. The current list of rules and regulations
- [x] A. Define where the document will be hosted 
- [x] B.  Define the format
- [x] C. Define the link from GitHub to the Mobile App
- [x] D. Define how the user transitions from a readable list to an editable list

2. The current list of proposals for selection
- [x] A.  Define how the proposals will be presented
- [x] B.  Ensure it flows with Status subsection of Voting section the DAO App https://github.com/tiki-bar/app/issues/566 

3. The current list of proposals for voting
- [x] A.Define how the proposals will be presented
- [x] B. Ensure it flows with **_Status subsection of Voting section the DAO App #566_**
- [ ] C.

4.. The jump-off for proposal submission
- [x] A. Define how the submission will tie in with **_Proposal Submission for DAO App #567_**

5. . The current list of top and bottom companies (as per the community selection).
- [ ] A.Write a draft set of rules for voting on a company's performance
- [ ] B. Sketch workflow for user voting process
- [ ] C. Sketch user's journey in company voting process
- [ ] D. Sketch wireframes for the user journey

![IMG_2105](https://user-images.githubusercontent.com/55149234/217526826-a07aac2b-1aa0-4c47-b9d3-83c74bee4a41.jpeg)

**Comment by BOC111** [comment]
**1. The current list of rules and regulations**

**Comment by BOC111** [comment]
2. **The current list of proposals for selection**

**Comment by BOC111** [comment]
3. **The current list of proposals for voting**

**Comment by BOC111** [comment]
4. **The current list of top and bottom companies**

Work up process and view

**Comment by mike-audi** [comment]
im not sure what I'm looking at here. 

if this is the Home Screen of the app that is supposed to be a dashboard of what's going on then this will need a well thought-thru design of what's highlighted. 

my suggestion tho is to NOT have a status screen/page and drop the user into the app with a 3 tab, tab bar at the bottom (rules, selection, vote). I think I would default the user to the vote page on log-in.

**Comment by BOC111** [comment]
My head is probably clearer this week. I am debating deleting this in favour of the flow stuff I have done this week.
